### ISSUE TITLE
Did not find config file: /opt/kitchen/client.rb

### ISSUE THREAD

**Issue by pantocrator27** [someara/kitchen-dokken#105]
Periodically I receive the following error:

```
[2017-05-10T01:21:21+00:00] WARN: *****************************************
[2017-05-10T01:21:21+00:00] WARN: Did not find config file: /opt/kitchen/client.rb, using command line options.
[2017-05-10T01:21:21+00:00] WARN: *****************************************
[2017-05-10T01:21:21+00:00] WARN: No cookbooks directory found at or above current directory.  Assuming /.
[2017-05-10T01:21:21+00:00] FATAL: Cannot load configuration from /opt/kitchen/dna.json
```

I do not know exactly what causes this but usually I can remedy the situation by doing a `kitchen destroy` followed by a `rm -rf ~/.dokken`

**Comment by someara** [comment]
Is this still an issue for you with 2.4.1?

**Comment by joestump** [comment]
Getting the same issue with the latest version as well.

**Comment by misheska** [comment]
Ditto here - basically anytime I try to do a `kitchen converge` more than once I get this with the `kitchen-dokken` in the ChefDK  2.1.11- didn't happen with the `kitchen-dokken` from the ChefDK 2.0.28. Other variable is that I upgraded Docker for Mac to latest.

Tried upgrading to `kitchen-dokken` 2.6.2 - didn't seem to help

**Comment by someara** [comment]
hitting this myself... investigating

**Comment by misheska** [comment]
Confirmed that downgrading to the ChefDK 2.0.28 serves as a workaround for the time-being.

**Comment by someara** [comment]
Found it! 2d01b66f40d6197865894dbb935aba86d4aadfc4
Fix released in 2.6.5

**Comment by hyeomans** [comment]
Newbie in `chef` and `dokken`, for future reference if you stumble upon this error just do: `gem update kitchen-dokken`

**Comment by iiro** [comment]
I upgraded to latest ChefDK (current) with kitchen-dokken 2.6.5 and could still reproduce it at times... I also downgraded to 2.0.28 - and this happens still at times - but not every time (not that repeatable)...

**Comment by misheska** [comment]
Confirming that this has been an intermittent issue for quite some time before this major blocker popped up. I even have video proof of this in my `Learning Chef for macOS and Linux video' ;-) https://www.safaribooksonline.com/library/view/learning-chef-for/9781491959442/video303777.html

I left a take in where I hit this problem so at least people would know how to work around the issue.

**Comment by someara** [comment]
Does this go away with ChefDK 2.2.2?

**Comment by misheska** [comment]
I think you meant to say ChefDK 2.2.1. Yes, with the ChefDK 2.2.1 I can converge more than once, so that issue seems to be fixed.

I just installed the new one after the announcement today, so I’ll know more about the intermittent error that happens after `client.rb` once I spend more time using Test Kitchen w/dokken today.

Thanks, looks like your fix addresses the main issue that was preventing us from upgrading to the ChefDK 2.1.11, as not being able to use dokken with Test Kitchen is a deal breaker for us.

**Comment by someara** [comment]
So I think newer ChefDK breaks the "chef gem install" to get the latest version of a gem

**Comment by someara** [comment]
Look at your /opt/chefdk/bin/kitchen file... it's using exact pins

**Comment by misheska** [comment]
The main issue is resolved, but the sporadic issue remains. I just saw it today when I ran `kitchen converge` multiple times. If it matters, I was doing a `kitchen destroy` and `kitchen create`. Then this happens sporadically:

```
$ kitchen destroy
-----> Starting Kitchen (v1.17.0)
-----> Destroying <default-centos7>...
       Deleting kitchen sandbox at /Users/misheska/.dokken/kitchen_sandbox/07bc26ea74-default-centos7
       Deleting verifier sandbox at /Users/misheska/.dokken/verifier_sandbox/07bc26ea74-default-centos7
       Finished destroying <default-centos7> (0m11.19s).
-----> Destroying <default-ubuntu1404>...
       Deleting kitchen sandbox at /Users/misheska/.dokken/kitchen_sandbox/07bc26ea74-default-ubuntu1404
       Deleting verifier sandbox at /Users/misheska/.dokken/verifier_sandbox/07bc26ea74-default-ubuntu1404
       Finished destroying <default-ubuntu1404> (0m0.03s).
-----> Kitchen is finished. (0m12.93s)
$ kitchen converge default-centos7
-----> Starting Kitchen (v1.17.0)
-----> Creating <default-centos7>...
       Creating kitchen sandbox at /Users/misheska/.dokken/kitchen_sandbox/07bc26ea74-default-centos7
       Creating verifier sandbox at /Users/misheska/.dokken/verifier_sandbox/07bc26ea74-default-centos7
       Building work image..
       Creating container 07bc26ea74-default-centos7
       Finished creating <default-centos7> (0m2.15s).
-----> Converging <default-centos7>...
       Creating kitchen sandbox in /Users/misheska/.dokken/kitchen_sandbox/07bc26ea74-default-centos7
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 6.3.1...
       Removing non-cookbook files before transfer
       Preparing validation.pem
       Preparing client.rb
[2017-09-12T17:52:02+00:00] WARN: *****************************************
[2017-09-12T17:52:02+00:00] WARN: Did not find config file: /opt/kitchen/client.rb, using command line options.
[2017-09-12T17:52:02+00:00] WARN: *****************************************
[2017-09-12T17:52:02+00:00] WARN: No cookbooks directory found at or above current directory.  Assuming /.
[2017-09-12T17:52:02+00:00] FATAL: Cannot load configuration from /opt/kitchen/dna.json
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Converge failed on instance <default-centos7>.  Please see .kitchen/logs/default-centos7.log for more details
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

**Comment by wolftrouble** [comment]
This is still a problem in my testing. I'm running ChefDK 2.2.1 on a Mac (newest version for MacOS). One thing to note is that /opt/kitchen is not a valid directory:

```
root@dokken:/opt# ls -l /opt
ls: cannot access '/opt/kitchen': No such file or directory
total 4
drwxrwxr-x 6 root root 4096 Sep 14 21:53 chef
d????????? ? ?    ?       ?            ? kitchen
drwxr-xr-x 2 root root   68 Sep 14 22:17 verifier
```

**Comment by wolftrouble** [comment]
I've been trying to do some digging into this and haven't been able to determine what's happening. Obviously a race condition of some kind is the most likely suspect but the code to setup the sandbox seems straightforward and unlikely to result in a race (mkdir+chmod, then simply reference the path in the docker config). I suspect a bug in the overlayfs2 implementation (as in a docker bug) but that's pretty hand-wavey.

**Comment by gavvvr** [comment]
kitchen-dokken (2.6.5), same issue when you run `kitchen test` for the 2nd time. What I do is just copy the YAML from **Usage** section of the readme and run simple Hello_world recipe. It works for the 1st time, for 2nd time it gives mentioned here error. You can then change `image` to another one (which you never tried to use before) and it will work only once.

**Comment by acondrat** [comment]
Same issue, running 2.6.5.

A simple way of reproducing it is to run in parallel with `kitchen test -p`.

**Comment by Purple90** [comment]
So interestingly enough, I ran `kitchen test -p` which actually was sucessful, and then I was able to run `kichen dokken` so thanks @acondrat 

I have no idea why, but before that, I was having the same issue as everyone else.

**Comment by AlexPerucchini** [comment]
This is still an intermittent issue:
kitchen-dokken (2.6.5) 
Chef Development Kit Version: 2.3.4
chef-client version: 13.4.19
delivery version: master (73ebb72a6c42b3d2ff5370c476be800fee7e5427)
berks version: 6.3.1
kitchen version: 1.17.0
inspec version: 1.36.1

Doing a kitchen destroy and kitchen test -p seems to consistently work.

**Comment by tas50** [comment]
@someara I get this error every time with the latest dokken in the latest ChefDK so new everything. It happens every time I try to test a box that already has a running container.

**Comment by daugustus** [comment]
Same problem here with:
kitchen-dokken (2.6.5)
Chef Development Kit Version: 2.4.17
chef-client version: 13.6.4
delivery version: master (73ebb72a6c42b3d2ff5370c476be800fee7e5427)
berks version: 6.3.1
kitchen version: 1.19.2
inspec version: 1.45.13

<kitchen test -p> fails *most* of the time

**Comment by docwhat** [comment]
- macOS: 10.13.2
- Chef Development Kit Version: 2.4.17 (installed via Homebrew)
- chef-client version: 13.6.4
- delivery version: master (73ebb72a6c42b3d2ff5370c476be800fee7e5427)
- berks version: 6.3.1
- kitchen version: 1.19.2
- inspec version: 1.45.13
- kitchen-dokken: 2.6.5
- Docker: 17.12.0-ce-rc4, build 6a2c058 (Native Mac Installer, not `docker-machine` or Boot2Docker)

This will generate the error 90% of the time:

```
$ kitchen destroy -c99 && kitchen converge -c99 && kitchen destroy -c99 && kitchen converge -c99
```

Equally, I can avoid the problem 99% of the time by adding `sleep 10` between the destroy and converge.

So it seems to be a timing issue of some kind.  Perhaps between the  Linux VM running docker and the macOS host?

**Comment by docwhat** [comment]
@someara Does the above help? If not, I can do a screen sharing session with you where you can try it out on my system where it is easy to break.

**Comment by ikari7789** [comment]
Testing #144 in my own environment and it seems to have fixed the issue. I needed to reset my Docker environment for Dokken though.

**Comment by tas50** [comment]
This should be fixed by the fix above. I'll get a release out today for this and we'll ship it in the next DK

1.

**Comment by ikari7789** [comment]
Hmmm. It happened again :/ Though it seems less constant than it was before.

**Comment by ikari7789** [comment]
Sorry, seems I forgot to clean up the existing environment for the cookbook I was trying to test. It's working now.

**Comment by gmccue** [comment]
@tas50 in the meantime, could you recommend a version of `ChefDK` where this issue doesn't exist? Or is it present in all versions of the DK? Thanks!

**Comment by docwhat** [comment]
@tas50 

I git cloned commit bbc5ba61def3a1e21d855c2e5124d378bd8cbba6 (it says it is release 2.6.7) and did a `gem build kitchen-dokken && gem install ./kitchen-dokken-2.6.7.gem` and tried out my test case:

``` console
# Starting from a clean state: nothing in docker and kitchen list is empty.
kitchen destroy && kitchen converge && kitchen destroy && kitchen converge
```

The first `kitchen converge` succeeded (which failed quiet often for me).

However, the second `kitchen converge` failed with the usual message.

So I wouldn't call this closed (yet).

**Comment by docwhat** [comment]
PS: You're missing tags for all the versions after July 2nd, 2017 (`2.5.1`).
PPS: https://rubygems.org/gems/kitchen-dokken doesn't show version 2.6.7

**Comment by tas50** [comment]
@docwhat You're right. We didn't have a Rakefile for running rake release and I ran it and didn't notice the whole thing blew up. Too much multitasking for me right now. I pushed the release with the tag and added a Rakefile so we make sure the tags are there in the future.

**Comment by tonan** [comment]
I still have the issue coming up. I am trying to execute this from jenkins which is running in a container.

JenkinsFile: https://github.com/tonan/opsworks-automate-demo/blob/dokken/Jenkinsfile

**Error**
```
   Preparing client.rb
D      Creating client.rb from {:node_name=>"install-centos-7", :checksum_path=>"/opt/kitchen/checksums", :file_cache_path=>"/opt/kitchen/cache", :file_backup_path=>"/opt/kitchen/backup", :cookbook_path=>["/opt/kitchen/cookbooks", "/opt/kitchen/site-cookbooks"], :data_bag_path=>"/opt/kitchen/data_bags", :environment_path=>"/opt/kitchen/environments", :node_path=>"/opt/kitchen/nodes", :role_path=>"/opt/kitchen/roles", :client_path=>"/opt/kitchen/clients", :user_path=>"/opt/kitchen/users", :validation_key=>"/opt/kitchen/validation.pem", :client_key=>"/opt/kitchen/client.pem", :chef_server_url=>"http://127.0.0.1:8889", :encrypted_data_bag_secret=>"/opt/kitchen/encrypted_data_bag_secret", :treat_deprecation_warnings_as_errors=>false, :named_run_list=>{}}
D      Attempting to execute command - try 1 of 1.
[2018-03-08T23:13:26+00:00] WARN: *****************************************
[2018-03-08T23:13:26+00:00] WARN: Did not find config file: /opt/kitchen/client.rb, using command line options.
[2018-03-08T23:13:26+00:00] WARN: *****************************************
[2018-03-08T23:13:26+00:00] WARN: No cookbooks directory found at or above current directory.  Assuming /.
[2018-03-08T23:13:26+00:00] WARN: No cookbooks directory found at or above current directory.  Assuming /.
[2018-03-08T23:13:26+00:00] FATAL: Cannot load configuration from /opt/kitchen/dna.json
[2018-03-08T23:13:26+00:00] FATAL: Cannot load configuration from /opt/kitchen/dna.json
```

**Comment by mmukherjee** [comment]
I am working with @tonan on this issue and here are some more details -

We are trying to making this work on a Jenkins installation which is running on a docker container. The pipeline script being used  is -
```
node(){
    docker.image('chef/chefdk:2.2.1').inside('-v /var/run/docker.sock:/var/run/docker.sock -v $HOME/.berkshelf:/root/.berkshelf --privileged'){
        stage ('checkout'){
            git branch: 'dokken', url: 'https://github.com/tonan/opsworks-automate-demo.git'
        }
        stage('Build') {
                sh 'gem install kitchen-dokken'
                sh 'berks install'
        }
        stage('Kitchen Test') {
            try{
                sh 'KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen list install-centos-7'
                sh 'KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen destroy install-centos-7'
                sh 'KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen list install-centos-7'
                sh 'KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen create install-centos-7'
                sh 'KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen list install-centos-7'
                sleep 10
                sh 'KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen converge install-centos-7'
                sh 'KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen list install-centos-7'
                sh 'KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen destroy install-centos-7'
            }
            catch(err){
                //echo (err)
            }
            finally{
                //sh 'KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen diagnose --all'
            }
        }
    }
}
```
..and we end up with the same error.

```
[workspace] Running shell script
+ gem install kitchen-dokken
WARNING:  You don't have /root/.chefdk/gem/ruby/2.4.0/bin in your PATH,
	  gem executables will not run.
Successfully installed kitchen-dokken-2.6.7
1 gem installed
[Pipeline] sh
[workspace] Running shell script
+ berks install
Resolving cookbook dependencies...
Fetching 'learn_chef_httpd' from source at .
Fetching 'test' from source at test/fixtures/cookbooks/test
Using audit (6.0.1)
Using chef-client (10.0.0)
Using compat_resource (12.19.1)
Using cron (5.0.1)
Using learn_chef_httpd (1.0.0) from source at .
Using logrotate (2.2.0)
Using mingw (2.0.2)
Using nginx (8.1.2)
Using nginx-hardening (3.0.0)
Using ohai (5.2.2)
Using openssl (8.1.2)
Using seven_zip (2.0.2)
Using test (1.0.0) from source at test/fixtures/cookbooks/test
Using windows (4.0.1)
Using yum-epel (3.1.0)
Using zypper (0.4.0)
Using build-essential (8.0.4)
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Kitchen Test)
[Pipeline] sh
[workspace] Running shell script
+ KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen list install-centos-7
Instance          Driver  Provisioner  Verifier  Transport  Last Action  Last Error
install-centos-7  Dokken  Dokken       Inspec    Dokken     Created      Kitchen::ActionFailed
[Pipeline] sh
[workspace] Running shell script
+ KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen destroy install-centos-7
-----> Starting Kitchen (v1.17.0)
-----> Destroying <install-centos-7>...
       Deleting kitchen sandbox at /root/.dokken/kitchen_sandbox/7be1fc6cdc-install-centos-7
       Deleting verifier sandbox at /root/.dokken/verifier_sandbox/7be1fc6cdc-install-centos-7
       Finished destroying <install-centos-7> (0m10.28s).
-----> Kitchen is finished. (0m11.84s)
[Pipeline] sh
[workspace] Running shell script
+ KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen list install-centos-7
Instance          Driver  Provisioner  Verifier  Transport  Last Action    Last Error
install-centos-7  Dokken  Dokken       Inspec    Dokken     <Not Created>  <None>
[Pipeline] sh
[workspace] Running shell script
+ KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen create install-centos-7
-----> Starting Kitchen (v1.17.0)
-----> Creating <install-centos-7>...
       Creating kitchen sandbox at /root/.dokken/kitchen_sandbox/7be1fc6cdc-install-centos-7
       Creating verifier sandbox at /root/.dokken/verifier_sandbox/7be1fc6cdc-install-centos-7
       Building work image..
       Creating container 7be1fc6cdc-install-centos-7
       Finished creating <install-centos-7> (0m3.24s).
-----> Kitchen is finished. (0m4.77s)
[Pipeline] sh
[workspace] Running shell script
+ KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen list install-centos-7
Instance          Driver  Provisioner  Verifier  Transport  Last Action  Last Error
install-centos-7  Dokken  Dokken       Inspec    Dokken     Created      <None>
[Pipeline] sleep
Sleeping for 10 sec
[Pipeline] sh
[workspace] Running shell script
+ KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen converge install-centos-7
-----> Starting Kitchen (v1.17.0)
-----> Converging <install-centos-7>...
       Creating kitchen sandbox in /root/.dokken/kitchen_sandbox/7be1fc6cdc-install-centos-7
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 6.3.1...
       Removing non-cookbook files before transfer
       Preparing roles
       Preparing validation.pem
       Preparing client.rb
[2018-03-09T03:18:49+00:00] WARN: *****************************************
[2018-03-09T03:18:49+00:00] WARN: Did not find config file: /opt/kitchen/client.rb, using command line options.
[2018-03-09T03:18:49+00:00] WARN: *****************************************
[2018-03-09T03:18:49+00:00] WARN: No cookbooks directory found at or above current directory.  Assuming /.
[2018-03-09T03:18:49+00:00] WARN: No cookbooks directory found at or above current directory.  Assuming /.
[2018-03-09T03:18:49+00:00] FATAL: Cannot load configuration from /opt/kitchen/dna.json
[2018-03-09T03:18:49+00:00] FATAL: Cannot load configuration from /opt/kitchen/dna.json
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Converge failed on instance <install-centos-7>.  Please see .kitchen/logs/install-centos-7.log for more details
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```
Where are we going wrong?

**Comment by PhilGrayson** [comment]
@mmukherjee I've had similar issues to you. This patch has worked around the issue for me.

[kitchen-dokken-issue-105.patch.txt](https://github.com/someara/kitchen-dokken/files/1796511/kitchen-dokken-issue-105.patch.txt)

**Comment by gmccue** [comment]
I'm having the same issue when running on CircleCI with a remote docker host. I've tried several workarounds without success. Is there a preferred/documented way to handle this scenario?

**Comment by tonan** [comment]
@someara is there a specific combination for the dokken driver and chef to make it work. For now if I am taking everything latest, i am facing the same error pretty much everytime in the scenario where kitchen dokken runs within a container.

**Scenario**
If test kitchen with dokken driver is executed in a chef/chefdk container, its unable to find client.rb and fails with the exact error as mentioned by @mmukherjee.

However if I am running the same converge on my mac or an EC2(ubuntu/centos) vm, with docker installed, it just works fine. (using the latest 2.6.7 kitchen-dokken gem for both scenarios)

Is it a current limitation for the kitchen-dokken driver that it errors out when running inside a container.

**Comment by cheeseplus** [comment]
Following up, as I've chatted with @sauravdevops in other channels:

- kitchen-dokken from inside a docker container doesn't work at this time w/ bind mounting
- this can be considered a current limitation as it's not something that works out of the box
- whether it is something that can be made to work or is in the design scope is another matter
- this issue, while sharing a similar error, was about a race condition, not Dokken from inside a container (it looks the same because when bind mounting fails for any reason, the error is presented)

For anyone in the thread trying to do this in CI/dokken-inside-docker, that's a different issue entirely and not a use case that is strictly supported at this time. Over the evolution of the driver this may have worked due to different mechanisms being used internally and if there is a working/supported configuration we will make that clear in the readme at that time.

**Comment by sauravdevops** [comment]
Thankyou @cheeseplus for taking the time to analyze and confirm on the limitation. This would be very helpful for many others like myself who are trying to put in kitchen tests in their pipeline. As the acceptance grows more towards container based CI solutions, this would be a great feature to have.

**Comment by ikari7789** [comment]
@cheeseplus do you know if there’s any particular reason why bind mounts are used over volumes? It seems volumes are a more standard, and the recommended, way of dealing with files between host + container.

**Comment by docwhat** [comment]
I can make this error happen 100% in a normal non-DinD setup. 

Also:  `/var/lib/docker` must be a volume mount to have DinD work.

**Comment by cheeseplus** [comment]
I honestly don't know why bind mounts were chosen - I've only just started digging into the code @ikari7789.

@docwhat to make sure we're capturing this - can you do this 100% of the time with 2.6.7 in new DK or just with parallel?

**Comment by docwhat** [comment]
I am unable to reproduce the problem using my test case from above with:

- Chef Development Kit Version: 2.5.3
- kitchen-dokken (2.6.7)

Yay!

**Comment by docwhat** [comment]
I still get this error when running in a DinD chefdk:2.5.8 container.

Should I file a new bug, @cheeseplus, for this?  I need it in order to do CI on my cookbooks.

**Comment by cheeseplus** [comment]
You probably should file a new bug but also that's not really a use case that is inherently supported at this time (based on what I've discovered and the intent I've been able to glean from the code).

**Comment by rspowell** [comment]
I'm using chefdk-3.7.23 and kitchen-dokken 2.6.7 and I'm getting the same errors. Jenkins is running on a VM and not in a container. Suggestions?
