### ISSUE TITLE
rsync failure on Linux hosts

### ISSUE THREAD

**Issue by hynd** [someara/kitchen-dokken#44]
```
chef --version
Chef Development Kit Version: 0.18.26
chef-client version: 12.14.89
delivery version: master (d86679335580be3de22996ef294b20d525889d8d)
berks version: 5.1.0
kitchen version: 1.13.0
```

kitchen-dokken works great on OSX (thanks!), but when trying to use it on a vanilla Linux host (Docker 1.12.3, Oracle Linux 6.8, 4.1.12-37.6.3.el6uek.x86_64 kernel) with the example .kitchen.yml from the README, i'm running into the following error:
```
$ kitchen converge
-----> Starting Kitchen (v1.13.0)
-----> Creating <default-centos-7>...
       Finished creating <default-centos-7> (0m1.58s).
-----> Converging <default-centos-7>...
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 5.1.0...
       Removing non-cookbook files before transfer
       Preparing validation.pem
       Preparing client.rb
       Transferring files to <default-centos-7>
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: unexplained error (code 254) at io.c(600) [sender=3.0.6]
[2016-11-29T14:15:05+00:00] WARN: *****************************************
[2016-11-29T14:15:05+00:00] WARN: Did not find config file: /opt/kitchen/client.rb, using command line options.
[2016-11-29T14:15:05+00:00] WARN: *****************************************
[2016-11-29T14:15:05+00:00] WARN: No cookbooks directory found at or above current directory.  Assuming /.
[2016-11-29T14:15:05+00:00] FATAL: Cannot load configuration from /opt/kitchen/dna.json
```

The failed `rsync` lines seem to be the key.  If i try to log into the data container (using the same ssh args passed to rsync by the dokken transport), i get booted out:
```
$ ssh -i /tmp/dokken/id_rsa -p 32784 root@0.0.0.0
Last login: Tue Nov 29 14:18:15 2016 from 172.17.0.1
Connection to 0.0.0.0 closed.
$ echo $?
254
```
(there's nothing particularly incriminating in a verbose output, save for a `debug1: Exit status 254` - the same `ssh` command on OSX works fine and i end up inside the data container)

Most suggestions (including Docker's own) seem to be either setting `UsePAM=no` in sshd's config, or comment out pam_loginuid.so (or making "optional") in _/etc/pam.d/sshd_:
https://docs.docker.com/engine/examples/running_ssh_service/

Either of those fix the above error, though i'm not entirely sure why... (possibly related to https://github.com/docker/docker/issues/8244 and/or Linux auditing breaking containers?).

Would you consider respinning someara/kitchen-cache with pam_loginuid.so set to "optional"?

Thanks!

**Comment by rmoriz** [comment]
Having the same error under the following circumstances:

- kitchen running on OSX 10.12.2
```shell
chef -v                      
Chef Development Kit Version: 1.1.16

chef exec gem list | grep kitchen
kitchen-dokken (1.0.9)
kitchen-ec2 (1.2.0)
kitchen-inspec (0.17.0)
kitchen-vagrant (0.21.1)
test-kitchen (1.14.2)
```

- AND using `docker-machine` to connect to a remote dockerd running on Linux (Ubuntu 16.04)

```shell
eval $(docker-machine env rambo)

env | grep DOCKER 
DOCKER_TLS_VERIFY=1
DOCKER_HOST=tcp://10.0.1.49:2376
DOCKER_CERT_PATH=/Users/rmoriz/.docker/machine/machines/rambo
DOCKER_MACHINE_NAME=rambo

```


Error:

```
chef exec kitchen setup
-----> Starting Kitchen (v1.14.2)
-----> Creating <dokken-default-chef12-debian>...
       Finished creating <dokken-default-chef12-debian> (1m40.32s).
-----> Converging <dokken-default-chef12-debian>...
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 5.2.0...
       Removing non-cookbook files before transfer
       Preparing data_bags
       Preparing secret
       Preparing validation.pem
       Preparing client.rb
       Transferring files to <dokken-default-chef12-debian>
Received disconnect from 10.0.1.49 port 32769:2: Too many authentication failures for root
Connection to 10.0.1.49 closed by remote host.
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: unexplained error (code 255) at /BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-51/rsync/io.c(453) [sender=2.6.9]
[2017-01-20T10:19:12+00:00] WARN: *****************************************
[2017-01-20T10:19:12+00:00] WARN: Did not find config file: /opt/kitchen/client.rb, using command line options.
[2017-01-20T10:19:12+00:00] WARN: *****************************************
[2017-01-20T10:19:12+00:00] WARN: No cookbooks directory found at or above current directory.  Assuming /.
[2017-01-20T10:19:12+00:00] FATAL: Cannot load configuration from /opt/kitchen/dna.json
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Converge failed on instance <dokken-default-chef12-debian>.  Please see .kitchen/logs/dokken-default-chef12-debian.log for more details
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```


output of `kitchen diagnose --all`
```
---
timestamp: 2017-01-20 10:25:17 UTC
kitchen_version: 1.14.2
plugins:
  driver:
    Dokken:
      class: Kitchen::Driver::Dokken
      version: 
      api_version: 
  provisioner:
    Dokken:
      class: Kitchen::Provisioner::Dokken
      version: 1.14.2
      api_version: 2
  transport:
    Dokken:
      class: Kitchen::Transport::Dokken
      version: 1.14.2
      api_version: 1
  verifier:
    Inspec:
      class: Kitchen::Verifier::Inspec
      version: 0.17.0
      api_version: 1
loader:
  process_erb: true
  process_local: true
  process_global: true
  global_config:
    filename: "/Users/rmoriz/.kitchen/config.yml"
    raw_data:
      driver:
        customize:
          memory: 2048
          cpus: 2
  project_config:
    filename: "/Users/rmoriz/project/chef/devops-project-base/.kitchen.dokken.yml"
    raw_data:
      driver:
        name: dokken
        chef_version: latest
      transport:
        name: dokken
      provisioner:
        name: dokken
      verifier:
        name: inspec
        root_path: "/opt/verifier"
        sudo: false
      platforms:
      - name: debian
        driver:
          vm_hostname: ci-project-base.project.com
          image: debian:jessie
          pid_one_command: "/bin/systemd"
          intermediate_instructions:
          - RUN /usr/bin/apt-get update
          - RUN /usr/bin/apt-get install -y cron
      suites:
      - name: dokken-default-chef12
        run_list:
        - recipe[project-base::default]
        attributes:
          project-base:
            slack_handler:
              enabled: false
            papertrail:
              enabled: true
  local_config: 
  combined_config:
    filename: 
    raw_data:
      driver:
        customize:
          memory: 2048
          cpus: 2
        name: dokken
        chef_version: latest
      transport:
        name: dokken
      provisioner:
        name: dokken
      verifier:
        name: inspec
        root_path: "/opt/verifier"
        sudo: false
      platforms:
      - name: debian
        driver:
          vm_hostname: ci-project-base.project.com
          image: debian:jessie
          pid_one_command: "/bin/systemd"
          intermediate_instructions:
          - RUN /usr/bin/apt-get update
          - RUN /usr/bin/apt-get install -y cron
      suites:
      - name: dokken-default-chef12
        run_list:
        - recipe[project-base::default]
        attributes:
          project-base:
            slack_handler:
              enabled: false
            papertrail:
              enabled: true
instances:
  dokken-default-chef12-debian:
    platform:
      os_type: unix
      shell_type: bourne
    state_file:
      chef_container:
        Id: e287090976509847ec9a72a7b206ab0f6ac9aca8bb11eb2d3f4d1bc58f09316a
        Created: '2017-01-20T10:17:48.968107864Z'
        Path: 'true'
        Args: []
        State:
          Status: created
          Running: false
          Paused: false
          Restarting: false
          OOMKilled: false
          Dead: false
          Pid: 0
          ExitCode: 0
          Error: ''
          StartedAt: '0001-01-01T00:00:00Z'
          FinishedAt: '0001-01-01T00:00:00Z'
        Image: sha256:40365a794afb73d26a7dfc7b860133e178b63196319d8fac6e444cd4d4c48b04
        ResolvConfPath: ''
        HostnamePath: ''
        HostsPath: ''
        LogPath: ''
        Name: "/chef-latest"
        RestartCount: 0
        Driver: aufs
        MountLabel: ''
        ProcessLabel: ''
        AppArmorProfile: ''
        ExecIDs: 
        HostConfig:
          Binds: 
          ContainerIDFile: ''
          LogConfig:
            Type: json-file
            Config: {}
          NetworkMode: default
          PortBindings: 
          RestartPolicy:
            Name: ''
            MaximumRetryCount: 0
          AutoRemove: false
          VolumeDriver: ''
          VolumesFrom: 
          CapAdd: 
          CapDrop: 
          Dns: 
          DnsOptions: 
          DnsSearch: 
          ExtraHosts: 
          GroupAdd: 
          IpcMode: ''
          Cgroup: ''
          Links: 
          OomScoreAdj: 0
          PidMode: ''
          Privileged: false
          PublishAllPorts: false
          ReadonlyRootfs: false
          SecurityOpt: 
          UTSMode: ''
          UsernsMode: ''
          ShmSize: 67108864
          ConsoleSize:
          - 0
          - 0
          Isolation: ''
          CpuShares: 0
          Memory: 0
          NanoCpus: 0
          CgroupParent: ''
          BlkioWeight: 0
          BlkioWeightDevice: 
          BlkioDeviceReadBps: 
          BlkioDeviceWriteBps: 
          BlkioDeviceReadIOps: 
          BlkioDeviceWriteIOps: 
          CpuPeriod: 0
          CpuQuota: 0
          CpuRealtimePeriod: 0
          CpuRealtimeRuntime: 0
          CpusetCpus: ''
          CpusetMems: ''
          Devices: 
          DiskQuota: 0
          KernelMemory: 0
          MemoryReservation: 0
          MemorySwap: 0
          MemorySwappiness: -1
          OomKillDisable: false
          PidsLimit: 0
          Ulimits: 
          CpuCount: 0
          CpuPercent: 0
          IOMaximumIOps: 0
          IOMaximumBandwidth: 0
        GraphDriver:
          Name: aufs
          Data: 
        Volumes:
          "/opt/chef": "/srv/docker/docker/volumes/5ed919d10c4b23732bdde0e284c1a06fbfd49d6c5da68c1703c49211c14ae539/_data"
        VolumesRW:
          "/opt/chef": true
        Config:
          Hostname: e28709097650
          Domainname: ''
          User: ''
          AttachStdin: false
          AttachStdout: false
          AttachStderr: false
          Tty: false
          OpenStdin: false
          StdinOnce: false
          Env:
          - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
          Cmd:
          - 'true'
          Image: chef/chef:latest
          Volumes:
            "/opt/chef": {}
          WorkingDir: ''
          Entrypoint: 
          OnBuild: 
          Labels: {}
          MacAddress: ''
          NetworkDisabled: false
          ExposedPorts: 
          VolumeDriver: ''
          Memory: 0
          MemorySwap: 0
          CpuShares: 0
          Cpuset: ''
        NetworkSettings:
          Bridge: ''
          SandboxID: ''
          HairpinMode: false
          LinkLocalIPv6Address: ''
          LinkLocalIPv6PrefixLen: 0
          Ports: 
          SandboxKey: ''
          SecondaryIPAddresses: 
          SecondaryIPv6Addresses: 
          EndpointID: ''
          Gateway: ''
          GlobalIPv6Address: ''
          GlobalIPv6PrefixLen: 0
          IPAddress: ''
          IPPrefixLen: 0
          IPv6Gateway: ''
          MacAddress: ''
      data_container:
        Id: fc8c56b292019d3f5e44e91dc09fa43c9b10aa5686cefd03f1938afffac81b4f
        Created: '2017-01-20T10:18:13.39373442Z'
        Path: "/usr/sbin/sshd"
        Args:
        - "-D"
        - "-p"
        - '22'
        - "-o"
        - UseDNS=no
        - "-o"
        - UsePrivilegeSeparation=no
        State:
          Status: running
          Running: true
          Paused: false
          Restarting: false
          OOMKilled: false
          Dead: false
          Pid: 9241
          ExitCode: 0
          Error: ''
          StartedAt: '2017-01-20T10:18:13.860200942Z'
          FinishedAt: '0001-01-01T00:00:00Z'
        Image: sha256:89f8b7258d937263bc323c204f07af49c51904c0f916eb040a21b382ac94ae83
        ResolvConfPath: "/srv/docker/docker/containers/fc8c56b292019d3f5e44e91dc09fa43c9b10aa5686cefd03f1938afffac81b4f/resolv.conf"
        HostnamePath: "/srv/docker/docker/containers/fc8c56b292019d3f5e44e91dc09fa43c9b10aa5686cefd03f1938afffac81b4f/hostname"
        HostsPath: "/srv/docker/docker/containers/fc8c56b292019d3f5e44e91dc09fa43c9b10aa5686cefd03f1938afffac81b4f/hosts"
        LogPath: "/srv/docker/docker/containers/fc8c56b292019d3f5e44e91dc09fa43c9b10aa5686cefd03f1938afffac81b4f/fc8c56b292019d3f5e44e91dc09fa43c9b10aa5686cefd03f1938afffac81b4f-json.log"
        Name: "/463855d9b6-dokken-default-chef12-debian-data"
        RestartCount: 0
        Driver: aufs
        MountLabel: ''
        ProcessLabel: ''
        AppArmorProfile: ''
        ExecIDs: 
        HostConfig:
          Binds: 
          ContainerIDFile: ''
          LogConfig:
            Type: json-file
            Config: {}
          NetworkMode: default
          PortBindings:
            22/tcp:
            - HostIp: ''
              HostPort: ''
          RestartPolicy:
            Name: ''
            MaximumRetryCount: 0
          AutoRemove: false
          VolumeDriver: ''
          VolumesFrom: 
          CapAdd: 
          CapDrop: 
          Dns: 
          DnsOptions: 
          DnsSearch: 
          ExtraHosts: 
          GroupAdd: 
          IpcMode: ''
          Cgroup: ''
          Links: 
          OomScoreAdj: 0
          PidMode: ''
          Privileged: false
          PublishAllPorts: true
          ReadonlyRootfs: false
          SecurityOpt: 
          UTSMode: ''
          UsernsMode: ''
          ShmSize: 67108864
          Runtime: runc
          ConsoleSize:
          - 0
          - 0
          Isolation: ''
          CpuShares: 0
          Memory: 0
          NanoCpus: 0
          CgroupParent: ''
          BlkioWeight: 0
          BlkioWeightDevice: 
          BlkioDeviceReadBps: 
          BlkioDeviceWriteBps: 
          BlkioDeviceReadIOps: 
          BlkioDeviceWriteIOps: 
          CpuPeriod: 0
          CpuQuota: 0
          CpuRealtimePeriod: 0
          CpuRealtimeRuntime: 0
          CpusetCpus: ''
          CpusetMems: ''
          Devices: 
          DiskQuota: 0
          KernelMemory: 0
          MemoryReservation: 0
          MemorySwap: 0
          MemorySwappiness: -1
          OomKillDisable: false
          PidsLimit: 0
          Ulimits: 
          CpuCount: 0
          CpuPercent: 0
          IOMaximumIOps: 0
          IOMaximumBandwidth: 0
        GraphDriver:
          Name: aufs
          Data: 
        Volumes:
          "/opt/kitchen": "/srv/docker/docker/volumes/72f566e66defa9502f473271d44c4a167c66bebe7590e755491ab0dd3c04d908/_data"
          "/opt/verifier": "/srv/docker/docker/volumes/461fef41d288a26445e54af5b8f64d04b3fd7722ac1ed457819c870ebbbc2159/_data"
        VolumesRW:
          "/opt/kitchen": true
          "/opt/verifier": true
        Config:
          Hostname: fc8c56b29201
          Domainname: ''
          User: ''
          AttachStdin: false
          AttachStdout: false
          AttachStderr: false
          Tty: false
          OpenStdin: false
          StdinOnce: false
          Env:
          - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
          - LANG=en_US.UTF-8
          Cmd:
          - "/usr/sbin/sshd"
          - "-D"
          - "-p"
          - '22'
          - "-o"
          - UseDNS=no
          - "-o"
          - UsePrivilegeSeparation=no
          Image: someara/kitchen-cache:latest
          Volumes:
            "/opt/kitchen": {}
            "/opt/verifier": {}
          WorkingDir: ''
          Entrypoint: 
          OnBuild: 
          Labels:
            License: GPLv2
            Vendor: CentOS
          MacAddress: ''
          NetworkDisabled: false
          ExposedPorts:
            22/tcp: {}
          VolumeDriver: ''
          Memory: 0
          MemorySwap: 0
          CpuShares: 0
          Cpuset: ''
        NetworkSettings:
          Bridge: ''
          SandboxID: ef0883b4e1059fa64dfc18b66aeab49dc8357b992ef994367c6519ba2fe6b0cf
          HairpinMode: false
          LinkLocalIPv6Address: ''
          LinkLocalIPv6PrefixLen: 0
          Ports:
            22/tcp:
            - HostIp: 0.0.0.0
              HostPort: '32769'
          SandboxKey: "/var/run/docker/netns/ef0883b4e105"
          SecondaryIPAddresses: 
          SecondaryIPv6Addresses: 
          EndpointID: c1bb2f6f0eaafa5a173cde83f31d172d91a3dfec4f378596d42165071cee59c1
          Gateway: 172.17.0.1
          GlobalIPv6Address: ''
          GlobalIPv6PrefixLen: 0
          IPAddress: 172.17.0.2
          IPPrefixLen: 16
          IPv6Gateway: ''
          MacAddress: 02:42:ac:11:00:02
      image_prefix: 
      instance_name: 463855d9b6-dokken-default-chef12-debian
      instance_platform_name: debian
      last_action: create
      last_error: Kitchen::ActionFailed
      platform_image: debian:jessie
      runner_container:
        Id: 259ba5ed1e61cb17c1982a048d0b6721533d0ff66223057d55f49c6afe4e9177
        Created: '2017-01-20T10:19:00.5239821Z'
        Path: "/bin/systemd"
        Args: []
        State:
          Status: running
          Running: true
          Paused: false
          Restarting: false
          OOMKilled: false
          Dead: false
          Pid: 11374
          ExitCode: 0
          Error: ''
          StartedAt: '2017-01-20T10:19:00.97643272Z'
          FinishedAt: '0001-01-01T00:00:00Z'
        Image: sha256:0507c8239e01e5671d04e87201205e2274294d209cafee03879296f7923aa3a1
        ResolvConfPath: "/srv/docker/docker/containers/259ba5ed1e61cb17c1982a048d0b6721533d0ff66223057d55f49c6afe4e9177/resolv.conf"
        HostnamePath: "/srv/docker/docker/containers/259ba5ed1e61cb17c1982a048d0b6721533d0ff66223057d55f49c6afe4e9177/hostname"
        HostsPath: "/srv/docker/docker/containers/259ba5ed1e61cb17c1982a048d0b6721533d0ff66223057d55f49c6afe4e9177/hosts"
        LogPath: "/srv/docker/docker/containers/259ba5ed1e61cb17c1982a048d0b6721533d0ff66223057d55f49c6afe4e9177/259ba5ed1e61cb17c1982a048d0b6721533d0ff66223057d55f49c6afe4e9177-json.log"
        Name: "/463855d9b6-dokken-default-chef12-debian"
        RestartCount: 0
        Driver: aufs
        MountLabel: ''
        ProcessLabel: ''
        AppArmorProfile: ''
        ExecIDs: 
        HostConfig:
          Binds: []
          ContainerIDFile: ''
          LogConfig:
            Type: json-file
            Config: {}
          NetworkMode: bridge
          PortBindings: {}
          RestartPolicy:
            Name: ''
            MaximumRetryCount: 0
          AutoRemove: false
          VolumeDriver: ''
          VolumesFrom:
          - chef-latest
          - 463855d9b6-dokken-default-chef12-debian-data
          CapAdd: []
          CapDrop: []
          Dns: 
          DnsOptions: 
          DnsSearch: 
          ExtraHosts: 
          GroupAdd: 
          IpcMode: ''
          Cgroup: ''
          Links: 
          OomScoreAdj: 0
          PidMode: ''
          Privileged: false
          PublishAllPorts: false
          ReadonlyRootfs: false
          SecurityOpt: []
          UTSMode: ''
          UsernsMode: ''
          ShmSize: 67108864
          Runtime: runc
          ConsoleSize:
          - 0
          - 0
          Isolation: ''
          CpuShares: 0
          Memory: 0
          NanoCpus: 0
          CgroupParent: ''
          BlkioWeight: 0
          BlkioWeightDevice: 
          BlkioDeviceReadBps: 
          BlkioDeviceWriteBps: 
          BlkioDeviceReadIOps: 
          BlkioDeviceWriteIOps: 
          CpuPeriod: 0
          CpuQuota: 0
          CpuRealtimePeriod: 0
          CpuRealtimeRuntime: 0
          CpusetCpus: ''
          CpusetMems: ''
          Devices: 
          DiskQuota: 0
          KernelMemory: 0
          MemoryReservation: 0
          MemorySwap: 0
          MemorySwappiness: -1
          OomKillDisable: false
          PidsLimit: 0
          Ulimits: 
          CpuCount: 0
          CpuPercent: 0
          IOMaximumIOps: 0
          IOMaximumBandwidth: 0
        GraphDriver:
          Name: aufs
          Data: 
        Volumes:
          "/opt/chef": "/srv/docker/docker/volumes/5ed919d10c4b23732bdde0e284c1a06fbfd49d6c5da68c1703c49211c14ae539/_data"
          "/opt/kitchen": "/srv/docker/docker/volumes/72f566e66defa9502f473271d44c4a167c66bebe7590e755491ab0dd3c04d908/_data"
          "/opt/verifier": "/srv/docker/docker/volumes/461fef41d288a26445e54af5b8f64d04b3fd7722ac1ed457819c870ebbbc2159/_data"
        VolumesRW:
          "/opt/chef": true
          "/opt/kitchen": true
          "/opt/verifier": true
        Config:
          Hostname: 259ba5ed1e61
          Domainname: ''
          User: ''
          AttachStdin: false
          AttachStdout: false
          AttachStderr: false
          Tty: false
          OpenStdin: false
          StdinOnce: false
          Env:
          - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
          Cmd:
          - "/bin/systemd"
          Image: 463855d9b6-dokken-default-chef12-debian:latest
          Volumes: 
          WorkingDir: ''
          Entrypoint: 
          OnBuild: 
          Labels: {}
          MacAddress: ''
          NetworkDisabled: false
          ExposedPorts: 
          VolumeDriver: ''
          Memory: 0
          MemorySwap: 0
          CpuShares: 0
          Cpuset: ''
        NetworkSettings:
          Bridge: ''
          SandboxID: 14fd94a6dbeceaf0f1a9502600125c368fd75c723c66af8ac38e784eff0e0757
          HairpinMode: false
          LinkLocalIPv6Address: ''
          LinkLocalIPv6PrefixLen: 0
          Ports: {}
          SandboxKey: "/var/run/docker/netns/14fd94a6dbec"
          SecondaryIPAddresses: 
          SecondaryIPv6Addresses: 
          EndpointID: 1b5cd26f097a22b1ef044dc4a904157d8d50d27e170c2c2a0022911f82a7e425
          Gateway: 172.17.0.1
          GlobalIPv6Address: ''
          GlobalIPv6PrefixLen: 0
          IPAddress: 172.17.0.3
          IPPrefixLen: 16
          IPv6Gateway: ''
          MacAddress: 02:42:ac:11:00:03
      work_image: 463855d9b6-dokken-default-chef12-debian
    driver:
      api_retries: 20
      binds: 
      cap_add: 
      cap_drop: 
      chef_image: chef/chef
      chef_version: latest
      customize:
        memory: 2048
        cpus: 2
      data_image: someara/kitchen-cache:latest
      dns: 
      dns_search: 
      docker_host_url: tcp://10.0.1.49:2376
      forward: 
      hostname: 
      image: debian:jessie
      image_prefix: 
      intermediate_instructions:
      - RUN /usr/bin/apt-get update
      - RUN /usr/bin/apt-get install -y cron
      kitchen_root: "/Users/rmoriz/project/chef/devops-project-base"
      links: 
      log_level: :info
      name: dokken
      network_mode: bridge
      pid_one_command: "/bin/systemd"
      privileged: false
      read_timeout: 3600
      security_opt: 
      test_base_path: "/Users/rmoriz/project/chef/devops-project-base/test/integration"
      vm_hostname: ci-project-base.project.com
      write_timeout: 3600
    provisioner:
      always_update_cookbooks: false
      attributes:
        project-base:
          slack_handler:
            enabled: false
          papertrail:
            enabled: true
      chef_client_path: "/bin/chef-client"
      chef_omnibus_install_options: 
      chef_omnibus_url: https://omnitruck.chef.io/install.sh
      chef_zero_host: 
      chef_zero_port: 8889
      client_rb: {}
      clients_path: 
      command_prefix: 
      config_path: 
      cookbook_files_glob: README.*,metadata.{json,rb},attributes/**/*,definitions/**/*,files/**/*,libraries/**/*,providers/**/*,recipes/**/*,resources/**/*,templates/**/*
      data_bags_path: "/Users/rmoriz/project/chef/devops-project-base/data_bags"
      data_path: 
      deprecations_as_errors: false
      encrypted_data_bag_secret_key_path: "/Users/rmoriz/project/chef/devops-project-base/encrypted_data_bag_secret_key"
      environments_path: 
      ftp_proxy: 
      http_proxy: 
      https_proxy: 
      json_attributes: true
      kitchen_root: "/Users/rmoriz/project/chef/devops-project-base"
      log_file: 
      log_level: auto
      max_retries: 1
      name: dokken
      named_run_list: {}
      nodes_path: 
      policyfile: 
      policyfile_path: 
      profile_ruby: false
      require_chef_omnibus: true
      retry_on_exit_code: []
      roles_path: 
      root_path: "/opt/kitchen"
      ruby_bindir: "/embedded/bin"
      run_list:
      - recipe[project-base::default]
      sudo: true
      sudo_command: sudo -E
      test_base_path: "/Users/rmoriz/project/chef/devops-project-base/test/integration"
      wait_for_retry: 30
    transport:
      docker_host_url: tcp://10.0.1.49:2376
      host_ip_override: false
      kitchen_root: "/Users/rmoriz/project/chef/devops-project-base"
      log_level: :info
      name: dokken
      read_timeout: 3600
      test_base_path: "/Users/rmoriz/project/chef/devops-project-base/test/integration"
      write_timeout: 3600
    verifier:
      chef_omnibus_root: "/opt/chef"
      command_prefix: 
      ftp_proxy: 
      http_proxy: 
      https_proxy: 
      inspec_tests: []
      kitchen_root: "/Users/rmoriz/project/chef/devops-project-base"
      log_level: :info
      name: inspec
      root_path: "/opt/verifier"
      sudo: false
      sudo_command: sudo -E
      suite_name: dokken-default-chef12
      test_base_path: "/Users/rmoriz/project/chef/devops-project-base/test/integration"
```

**Comment by someara** [comment]
Fixed up in 2.0.0

**Comment by rmoriz** [comment]
Still having this issue with Dokken 2.1.2

- cleaned local cache directory
- removed all images on the remote docker host


```-----> Creating <asdf-debian-8>...
       Creating kitchen sandbox at /Users/rmoriz/.dokken/kitchen_sandbox/463855d9b6-asdf-debian-8
       Creating verifier sandbox at /Users/rmoriz/.dokken/verifier_sandbox/463855d9b6-asdf-debian-8
       Building work image..
       Finished creating <asdf-debian-8> (2m48.21s).
-----> Converging <asdf-debian-8>...
       Creating kitchen sandbox in /Users/rmoriz/.dokken/kitchen_sandbox/463855d9b6-asdf-debian-8
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 5.6.3...
       Removing non-cookbook files before transfer
       Preparing data_bags
       Preparing secret
       Preparing validation.pem
       Preparing client.rb
[2017-03-18T11:26:44+00:00] WARN: *****************************************
[2017-03-18T11:26:44+00:00] WARN: Did not find config file: /opt/kitchen/client.rb, using command line options.
[2017-03-18T11:26:44+00:00] WARN: *****************************************
[2017-03-18T11:26:44+00:00] WARN: No cookbooks directory found at or above current directory.  Assuming /.
[2017-03-18T11:26:44+00:00] FATAL: Cannot load configuration from /opt/kitchen/dna.json
```

**Comment by rmoriz** [comment]
related: https://github.com/someara/kitchen-dokken/issues/79

**Comment by KovRon** [comment]
Hi everyone!
I have the same issue. I've tried several versions from 2.1.2 to 1.0.0 and in my case the issue gone only with 0.0.35 version.
