### ISSUE TITLE
Not using the most recent version of Chef

### ISSUE THREAD

**Issue by kylegoch** [someara/kitchen-dokken#55]
With this kitchen.yml
```
---
driver:
  name: dokken
  chef_version: latest
  privileged: true
transport:
  name: dokken
provisioner:
  name: dokken

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
    driver:
      image: ubuntu:16.04
      pid_one_command: /sbin/init
      intermediate_instructions:
        - RUN /usr/bin/apt-get update
        - RUN /usr/bin/apt-get install apt-transport-https net-tools -y

suites:
  - name: default
    run_list:
      - recipe[chef_role_jenkins::default]
    verifier:
      inspec_tests:
        - test/recipes
    attributes:
```

I am getting chef version 12.16.42 instead of 12.77.44. I thought it was becuase my ChefDK was one version behind, but I updated and still have the issue.

Is there something I may have missed somewhere that has me stuck on 12.16.42?

**Comment by rmoriz** [comment]
1. `chef_version:latest` is using the "latest" tag from https://hub.docker.com/r/chef/chef/tags/ 

      the `latest` tag should match the current stable release of chef as displayed on `https://downloads.chef.io/chef` - use `current` if you want to use the `current` releases.

2. As far as I understand, you need to manually update the local image once it has been pulled by dokken, see:

- https://github.com/someara/kitchen-dokken/blob/8e0392de163a2945786faaee7e8e82a66676d956/lib/kitchen/driver/dokken.rb#L260
- https://github.com/someara/kitchen-dokken/blob/8e0392de163a2945786faaee7e8e82a66676d956/lib/kitchen/driver/dokken.rb#L380

e.g. `docker pull chef/chef:latest` on the shell

**Comment by kylegoch** [comment]
Thanks for the reply @rmoriz !

I ran `docker pull chef/chef:latest` but it said i already had the latest.

Running `docker images` showed the chef/chef:latest in the list

I manually changed `chef_version: latest` to `chef_version: 12.17.44` and its running 12.17.44.
Running `docker images` now shows both chef/chef:latest AND chef/chef:12.17.44. They have the same image ID so im baffled.

I did notice that I have a someara/chef:latest in my images as well, and that one is about 8 weeks old. However looking in [https://hub.docker.com/r/someara/chef/tags/](https://hub.docker.com/r/someara/chef/tags/), 'latest' is 2 months old, but there is a 12.17.44 version. And the image i have locally is 2 months old.

**Comment by rmoriz** [comment]
AFAIK chef, Inc. took over the maintanance of the chef image a while ago, see https://github.com/someara/kitchen-dokken/commit/eea77c0b2b635973a97e172b36f0f95cf8253b03

Maybe you were still using an older release that points to the `someara/chef` image which indeed is stale/obsolete now.

**Comment by kylegoch** [comment]
So i purged all my kitchen and dokken related images to start fresh. Then ran a converge. Still on 12.16.42 despite `chef_version: latest`. However I no longer have someara/chef images and have only chef/chef: latest.

```
09:55 $ docker images
REPOSITORY                       TAG                 IMAGE ID            CREATED             SIZE
2aca6985a8-default-ubuntu-1604   latest              ab49955e12f1        22 seconds ago      185 MB
chef/chef                        latest              40365a794afb        4 weeks ago         124 MB
ubuntu                           16.04               4ca3a192ff2a        7 weeks ago         128 MB
someara/kitchen-cache            latest              89f8b7258d93        14 months ago       301 MB
```

```
09:56 $ kitchen converge
-----> Starting Kitchen (v1.14.2)
-----> Creating <default-ubuntu-1604>...
       Finished creating <default-ubuntu-1604> (1m1.91s).
-----> Converging <default-ubuntu-1604>...
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 5.2.0...
       Removing non-cookbook files before transfer
       Preparing validation.pem
       Preparing client.rb
       Transferring files to <default-ubuntu-1604>
Starting Chef Client, version 12.16.42
Creating a new client identity for default-ubuntu-1604 using the validator key.
```

**Comment by rmoriz** [comment]
```shell
docker run --rm -it chef/chef:latest cat /opt/chef/version-manifest.txt 
chef 12.17.44
```


you probably need to destory the kitchen and recreate it.

**Comment by kylegoch** [comment]
```
11:28 $ docker run --rm -it chef/chef:latest cat /opt/chef/version-manifest.txt
chef 12.17.44
```

But kitchen still says:
```
Starting Chef Client, version 12.16.42
```


Not sure if related, but if i do `kitchen converge` and it fails, i fix the problem, then go do `kitchen converge` again it says this:
```
Starting Chef Client, version 12.16.42
[2017-01-23T16:14:56+00:00] WARN: Port 8889 not available
[2017-01-23T16:14:56+00:00] WARN: Chef client 290 is running, will wait for it to finish and then run.
[2017-01-23T16:15:58+00:00] WARN: Port 8889 not available
[2017-01-23T16:15:58+00:00] WARN: Port 8890 not available
[2017-01-23T16:15:58+00:00] WARN: Chef client 290 is running, will wait for it to finish and then run.
```

Whereas previously it would just re-converge the node and update the changed resources.

I also noticed i was on dokken 1.0.9, but updating to latest version did not change anything.

**Comment by someara** [comment]
Fixed up in 2.0.0

**Comment by kylegoch** [comment]
Thanks @someara for getting that squared away!

Updated to 2.0.1, the chef version is fixed. Still getting the chef client error above, meaning its probably not related. Will open a new issue.
